version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_worker
    ports:
      - 81:80
      - 443:443
    volumes:
      - "${DOCKER_FOLDER}/nginx/config:/etc/nginx/conf.d"
      - "${DOCKER_FOLDER}/nginx/include:/etc/nginx/include"
      - "${HOME_SERVER_FOLDER}/logs:/var/www/logs"
      - "${HOME_SERVER_FOLDER}/logs/nginx:/var/www/logs/nginx"
      - "${HOME_SERVER_FOLDER}:/var/www:cached"
      - "${DOCKER_FOLDER}/share:/share"
    links:
      - php-7.2
    networks:
      internal:
        ipv4_address: 192.168.220.7
  db:
    container_name: db_worker
    restart: always
    image: mysql
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'codexdb'
    volumes:
      - "${DOCKER_FOLDER}/share:/share"
    networks:
      - internal
  db_5_7:
    container_name: db_57_worker
    restart: always
    image: mysql:5.7
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'codexdb'
    volumes:
      - "${DOCKER_FOLDER}/share:/share"
    networks:
      - internal
  php-7.2:
    container_name: php_72_worker
    image: artwake/php-7.2
    volumes:
      - "${HOME_SERVER_FOLDER}:/var/www:cached"
      - "${DOCKER_FOLDER}/share:/share"
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - db
      - db_5_7
      - redis
    networks:
      - internal
  redis:
    container_name: redis_worker
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "${DOCKER_FOLDER}/share:/share"
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
